services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: delitos_db
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: delitos_tucuman
      POSTGRES_USER: delitos_user
      POSTGRES_PASSWORD: delitos_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U delitos_user -d delitos_tucuman']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
